name: Delete_infra_AWS
env:
  S3_BACKET_NAME      : "bucket-for-tfstate"
  AWS_REGION_NAME     : "eu-central-1"

on:
  schedule:
    #- cron: '20/20 8-21 5,6 * *'

jobs:
  killall:
    name: 'Terraform_destroy'
    runs-on: ubuntu-latest
    environment: production
      
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Git Clone our repo
      uses: actions/checkout@v2


    - name: AWS configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id  : init
      run: terraform init

    - name: Copy zip with tfstate files from S3
      run: KEY=`aws s3 ls ${{ env.S3_BACKET_NAME }} | sort | tail -n 1 | awk '{print $4}'` && aws s3 cp s3://${{ env.S3_BACKET_NAME }}/$KEY .

    - name: Unzip tfstate files
      run: unzip \*.zip -d . terraform.tfstate


    #- name: Terraform destroy
    #  run: terraform destroy -auto-approve
