name: Create_infra_AWS
env:
  S3_BACKET_NAME      : "bucket-for-tfstate"
  APP_NAME            : "TestWebPage"
  STATE_FILE_NAME     : "tfstate_files_${{ github.sha }}.zip"
  AWS_REGION_NAME     : "eu-central-1"

on:
  push:
    branches:
    - main

jobs:
   killAll:
    name: 'Terraform_destroy'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Git Clone our repo
      uses: actions/checkout@v2


    - name: AWS configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id  : init
      run: terraform init
      
    - name: Copy Github Action from the core rep with the AWS CLI
      run: aws s3 cp s3://tfstate_files_246c86b08ecc3ad5bf2121a38b1e63c13ed3bfeb.zip ./
        
    - name: unzip
      run: unzip tfstate_files_246c86b08ecc3ad5bf2121a38b1e63c13ed3bfeb.zip ./


    - name: Terraform destroy
      run: terraform destroy -auto-approve
